### ISSUE TITLE
Error occurred when building mull in local development

### ISSUE THREAD

**Issue by haruming** [mull-project/mull#733] opened 2020-06-24 02:27 UTC
Hi, my OS is centOS so I have to build mull manually. I followed the instructions on the documentation. I finished installing LLVM and then built mull. After executing `make mull-cxx`, I got this error.
![image](https://user-images.githubusercontent.com/16981363/85490962-4233bc80-b605-11ea-9f3d-e7d4eb5be404.png)
I have no idea how to fix it. Could you give me a hint? Thanks!

**Comment by AlexDenisov** [comment] 2020-06-24 06:22
Hi @haruming, thank you for bringing this up. I just merged the relevant fix #730. Could you pull and give it another try? 

Also, we didn't test Mull on CentOS, so any feedback would be highly appreciated!

**Comment by AlexDenisov** [comment] 2020-10-16 09:28
I guess this one can be closed. Feel free to re-open if the issue is still there.

**Closed by AlexDenisov** 2020-10-16 09:28 UTC
