### ISSUE TITLE
I'm getting an `Assertion failed: (module && "Could not load module")`

### ISSUE THREAD

**Issue by bogado** [mull-project/mull#521] opened 2019-05-24 22:40 UTC
I was trying to follow the instructions and when I finally got mull to load some of the bitcode, apparently there was something wrong : 

```
$ mull-cxx -test-framework=CustomTest -compdb-path=./compile_commands.json -mutators=replace_assignment_mutator test_executable
Extracting bitcode from executable (threads: 1): 1/1. Finished in 2588ms.
Loading bitcode files (threads: 12): 499/694
parseBitcodeFile failed: Invalid bitcode signature
Loading bitcode files (threads: 12): 511/694Assertion failed: (module && "Could not load module"), function operator(), file ../tools/driver-cxx/driver-cxx.cpp, line 63.
Abort trap: 6
```

I've installed the latest binary for MacOSX.

**Comment by AlexDenisov** [comment] 2019-05-25 05:45
Hi @bogado, which version of Clang did you use to compile the binary?
The error message is hidden in the output: `parseBitcodeFile failed: Invalid bitcode signature`.

If I recall correctly, it happens when you use Clang from Xcode. Could that be the case?

**Comment by bogado** [comment] 2019-05-25 16:00
Yes I believe so, I am not 100% familiar with development in MacOS. I have pretty much the standard setup. 

I don't know if I can deviate too much of this setup thought. Do you think it would help if I compile mull with the same setup?

Thanks,
Victor Bogado

**Comment by AlexDenisov** [comment] 2019-05-25 19:40
@bogado, unfortunately you would have to use custom Clang compiler on macOS: the one that comes with Xcode does not play well with tools like Mull.

I would definitely recommend getting a recent version of LLVM/Clang from the official web page: http://releases.llvm.org/download.html#8.0.0.
You can unpack the archive and put it somewhere (my favourite place is `/opt/llvm/<version>`), and then use that clang while compiling your project, e.g.:

```
export CC=/opt/llvm/8.0.0/bin/clang
export CXX=/opt/llvm/8.0.0/bin/clang++
cmake ../path-to-project
make
```

Please, let me know if 'custom' LLVM/Clang solves the problem.

**Comment by bogado** [comment] 2019-05-28 23:44
Not to me, but I guess that this is the expected support level for the project. Maybe a note on the readme warning the next "me" that comes along would be enough. :D

**Comment by AlexDenisov** [comment] 2019-05-29 04:37
@bogado, sorry, I thought it's there, thanks for the patch! 😅

**Comment by AlexDenisov** [comment] 2019-06-15 08:28
@bogado so did it work in the end? Shall we close this issue?

**Comment by AlexDenisov** [comment] 2019-07-09 09:27
@bogado please, reopen if the issue is not resolved yet.

**Closed by AlexDenisov** 2019-07-09 09:27 UTC

**Comment by bogado** [comment] 2019-07-09 20:26
I'm sorry for not replying sooner, I couldn't make it work after all. Our application have a bunch of dependencies that may have got the flag.

Unfortunately I had limited time to spend trying to figure this out so I had to stop. I may retry in the future as I feel like this is desperately needed.
