### ISSUE TITLE
The Makefile does not work on Ubuntu.

### ISSUE THREAD

**Issue by Brick7Face** [mull-project/mull#367] opened 2018-07-07 02:43 UTC
I don't know what the hell is going on with BuildNinja but it cannot find the file and it's infuriating, as I have installed it and followed the instructions to a tee. I've tried finding more information on ninja not being included, but there's really not a lot of documentation out there. I really want to use Mull to mutate a project I'm working on, as there are virtually no other mutation tools for C. Here is the error after running "make install":

cd /opt/mull/BuildNinja && ninja mull-driver
/bin/sh: 1: cd: can't cd to /opt/mull/BuildNinja
Makefile:63: recipe for target 'ninja.build.mull-driver' failed
make: *** [ninja.build.mull-driver] Error 2

**Comment by AlexDenisov** [comment] 2018-07-10 19:24
Hi @Brick7Face, one step is missing from documentation: you need to initialize the build system first.
Try one of these:
```
# macOS
make ninja.init LLVM_ROOT=/opt/llvm-3.9
# Linux
make ninja.init LLVM_ROOT=/usr/lib/llvm-3.9
```

Please let me know if you have any other issues.

**Comment by Brick7Face** [comment] 2018-07-11 02:11
I'll have to mess with this later; there's a bunch of subcommands failing now and I'm not sure what's happening. Here's the log (very sorry for all the text) if you happen to have any quick fixes in the meantime. Thank you very much for your help either way.

cd /opt/mull/BuildNinja && ninja mull-driver
ninja: no work to do.
Resulting binary:
/opt/mull/BuildNinja/tools/driver/mull-driver
cd /opt/mull/BuildNinja && ninja install
[1/2] Linking CXX executable tools/reporter/mull-reporter
FAILED: : && /usr/bin/c++     -L/usr/lib/llvm-6.0/lib  -Wl,-undefined,dynamic_lookup -lLLVM-6.0 -lsqlite3 tools/reporter/CMakeFiles/mull-reporter.dir/WeakTestsReporter.cpp.o tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o  -o tools/reporter/mull-reporter  -Wl,-rpath,:::::::::::::::::::::::::::::::::::: && :
tools/reporter/CMakeFiles/mull-reporter.dir/WeakTestsReporter.cpp.o: In function `fetchKilledMutants(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
WeakTestsReporter.cpp:(.text+0x46): undefined reference to `sqlite3_open'
WeakTestsReporter.cpp:(.text+0xb5): undefined reference to `sqlite3_prepare'
WeakTestsReporter.cpp:(.text+0xd0): undefined reference to `sqlite3_step'
WeakTestsReporter.cpp:(.text+0xf6): undefined reference to `sqlite3_column_text'
WeakTestsReporter.cpp:(.text+0x14e): undefined reference to `sqlite3_errmsg'
WeakTestsReporter.cpp:(.text+0x162): undefined reference to `sqlite3_close'
WeakTestsReporter.cpp:(.text+0x179): undefined reference to `sqlite3_close'
tools/reporter/CMakeFiles/mull-reporter.dir/WeakTestsReporter.cpp.o: In function `readReportFromSQLite(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)':
WeakTestsReporter.cpp:(.text+0x26c): undefined reference to `sqlite3_open'
WeakTestsReporter.cpp:(.text+0x2f9): undefined reference to `sqlite3_prepare'
WeakTestsReporter.cpp:(.text+0x317): undefined reference to `sqlite3_step'
WeakTestsReporter.cpp:(.text+0x363): undefined reference to `sqlite3_column_text'
WeakTestsReporter.cpp:(.text+0x3bd): undefined reference to `sqlite3_column_text'
WeakTestsReporter.cpp:(.text+0x408): undefined reference to `sqlite3_column_int'
WeakTestsReporter.cpp:(.text+0x486): undefined reference to `sqlite3_column_text'
WeakTestsReporter.cpp:(.text+0x4d1): undefined reference to `sqlite3_column_int'
WeakTestsReporter.cpp:(.text+0x554): undefined reference to `sqlite3_column_int64'
WeakTestsReporter.cpp:(.text+0x58a): undefined reference to `sqlite3_column_text'
WeakTestsReporter.cpp:(.text+0x5e4): undefined reference to `sqlite3_column_text'
WeakTestsReporter.cpp:(.text+0x62f): undefined reference to `sqlite3_column_int'
WeakTestsReporter.cpp:(.text+0x655): undefined reference to `sqlite3_column_int'
WeakTestsReporter.cpp:(.text+0x6d4): undefined reference to `sqlite3_column_text'
WeakTestsReporter.cpp:(.text+0xa15): undefined reference to `sqlite3_errmsg'
WeakTestsReporter.cpp:(.text+0xa2c): undefined reference to `sqlite3_close'
WeakTestsReporter.cpp:(.text+0xa46): undefined reference to `sqlite3_close'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `main':
reporter.cpp:(.text+0x22): undefined reference to `llvm::cl::TopLevelSubCommand'
reporter.cpp:(.text+0x34): undefined reference to `llvm::cl::HideUnrelatedOptions(llvm::cl::OptionCategory&, llvm::cl::SubCommand&)'
reporter.cpp:(.text+0x7b): undefined reference to `llvm::cl::ParseCommandLineOptions(int, char const* const*, llvm::StringRef, llvm::raw_ostream*)'
reporter.cpp:(.text+0x85): undefined reference to `llvm::cl::SubCommand::operator bool() const'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o:(.data+0x0): undefined reference to `llvm::DisableABIBreakingChecks'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::SmallPtrSetImplBase::insert_imp(void const*)':
reporter.cpp:(.text._ZN4llvm19SmallPtrSetImplBase10insert_impEPKv[_ZN4llvm19SmallPtrSetImplBase10insert_impEPKv]+0x20c): undefined reference to `llvm::SmallPtrSetImplBase::insert_imp_big(void const*)'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::OptionCategory::OptionCategory(llvm::StringRef, llvm::StringRef)':
reporter.cpp:(.text._ZN4llvm2cl14OptionCategoryC2ENS_9StringRefES2_[_ZN4llvm2cl14OptionCategoryC5ENS_9StringRefES2_]+0x60): undefined reference to `llvm::cl::OptionCategory::registerCategory()'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::SubCommand::SubCommand(llvm::StringRef, llvm::StringRef)':
reporter.cpp:(.text._ZN4llvm2cl10SubCommandC2ENS_9StringRefES2_[_ZN4llvm2cl10SubCommandC5ENS_9StringRefES2_]+0x9f): undefined reference to `llvm::cl::SubCommand::registerSubCommand()'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::Option::Option(llvm::cl::NumOccurrencesFlag, llvm::cl::OptionHidden)':
reporter.cpp:(.text._ZN4llvm2cl6OptionC2ENS0_18NumOccurrencesFlagENS0_12OptionHiddenE[_ZN4llvm2cl6OptionC5ENS0_18NumOccurrencesFlagENS0_12OptionHiddenE]+0x13): undefined reference to `vtable for llvm::cl::Option'
reporter.cpp:(.text._ZN4llvm2cl6OptionC2ENS0_18NumOccurrencesFlagENS0_12OptionHiddenE[_ZN4llvm2cl6OptionC5ENS0_18NumOccurrencesFlagENS0_12OptionHiddenE]+0xe1): undefined reference to `llvm::cl::GeneralCategory'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::GenericOptionValue::GenericOptionValue()':
reporter.cpp:(.text._ZN4llvm2cl18GenericOptionValueC2Ev[_ZN4llvm2cl18GenericOptionValueC5Ev]+0x9): undefined reference to `vtable for llvm::cl::GenericOptionValue'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::parser<bool>::parser(llvm::cl::Option&)':
reporter.cpp:(.text._ZN4llvm2cl6parserIbEC2ERNS0_6OptionE[_ZN4llvm2cl6parserIbEC5ERNS0_6OptionE]+0x1f): undefined reference to `llvm::cl::basic_parser<bool>::basic_parser(llvm::cl::Option&)'
reporter.cpp:(.text._ZN4llvm2cl6parserIbEC2ERNS0_6OptionE[_ZN4llvm2cl6parserIbEC5ERNS0_6OptionE]+0x24): undefined reference to `vtable for llvm::cl::parser<bool>'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::parser<int>::parser(llvm::cl::Option&)':
reporter.cpp:(.text._ZN4llvm2cl6parserIiEC2ERNS0_6OptionE[_ZN4llvm2cl6parserIiEC5ERNS0_6OptionE]+0x1f): undefined reference to `llvm::cl::basic_parser<int>::basic_parser(llvm::cl::Option&)'
reporter.cpp:(.text._ZN4llvm2cl6parserIiEC2ERNS0_6OptionE[_ZN4llvm2cl6parserIiEC5ERNS0_6OptionE]+0x24): undefined reference to `vtable for llvm::cl::parser<int>'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::parser(llvm::cl::Option&)':
reporter.cpp:(.text._ZN4llvm2cl6parserINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEC2ERNS0_6OptionE[_ZN4llvm2cl6parserINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEC5ERNS0_6OptionE]+0x1f): undefined reference to `llvm::cl::basic_parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::basic_parser(llvm::cl::Option&)'
reporter.cpp:(.text._ZN4llvm2cl6parserINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEC2ERNS0_6OptionE[_ZN4llvm2cl6parserINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEC5ERNS0_6OptionE]+0x24): undefined reference to `vtable for llvm::cl::parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::ManagedStatic<llvm::cl::SubCommand, llvm::object_creator<llvm::cl::SubCommand>, llvm::object_deleter<llvm::cl::SubCommand> >::operator*()':
reporter.cpp:(.text._ZN4llvm13ManagedStaticINS_2cl10SubCommandENS_14object_creatorIS2_EENS_14object_deleterIS2_EEEdeEv[_ZN4llvm13ManagedStaticINS_2cl10SubCommandENS_14object_creatorIS2_EENS_14object_deleterIS2_EEEdeEv]+0x3a): undefined reference to `llvm::ManagedStaticBase::RegisterManagedStatic(void* (*)(), void (*)(void*)) const'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::Option::~Option()':
reporter.cpp:(.text._ZN4llvm2cl6OptionD2Ev[_ZN4llvm2cl6OptionD5Ev]+0xd): undefined reference to `vtable for llvm::cl::Option'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::OptionValue<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::OptionValue()':
reporter.cpp:(.text._ZN4llvm2cl11OptionValueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEC2Ev[_ZN4llvm2cl11OptionValueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEC5Ev]+0x19): undefined reference to `vtable for llvm::cl::OptionValue<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::OptionValue<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~OptionValue()':
reporter.cpp:(.text._ZN4llvm2cl11OptionValueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEED2Ev[_ZN4llvm2cl11OptionValueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEED5Ev]+0xd): undefined reference to `vtable for llvm::cl::OptionValue<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::opt<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false, llvm::cl::parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::opt<char [14], llvm::cl::desc, llvm::cl::cat, llvm::cl::NumOccurrencesFlag, llvm::cl::sub>(char const (&) [14], llvm::cl::desc const&, llvm::cl::cat const&, llvm::cl::NumOccurrencesFlag const&, llvm::cl::sub const&)':
reporter.cpp:(.text._ZN4llvm2cl3optINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0ENS0_6parserIS7_EEEC2IJA14_cNS0_4descENS0_3catENS0_18NumOccurrencesFlagENS0_3subEEEEDpRKT_[_ZN4llvm2cl3optINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0ENS0_6parserIS7_EEEC5IJA14_cNS0_4descENS0_3catENS0_18NumOccurrencesFlagENS0_3subEEEEDpRKT_]+0x4a): undefined reference to `vtable for llvm::cl::opt<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false, llvm::cl::parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >'
reporter.cpp:(.text._ZN4llvm2cl3optINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0ENS0_6parserIS7_EEEC2IJA14_cNS0_4descENS0_3catENS0_18NumOccurrencesFlagENS0_3subEEEEDpRKT_[_ZN4llvm2cl3optINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0ENS0_6parserIS7_EEEC5IJA14_cNS0_4descENS0_3catENS0_18NumOccurrencesFlagENS0_3subEEEEDpRKT_]+0x9d): undefined reference to `llvm::cl::opt<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false, llvm::cl::parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::done()'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::opt<int, false, llvm::cl::parser<int> >::opt<char [12], llvm::cl::desc, llvm::cl::value_desc, llvm::cl::cat, llvm::cl::sub, llvm::cl::initializer<int>, llvm::cl::NumOccurrencesFlag>(char const (&) [12], llvm::cl::desc const&, llvm::cl::value_desc const&, llvm::cl::cat const&, llvm::cl::sub const&, llvm::cl::initializer<int> const&, llvm::cl::NumOccurrencesFlag const&)':
reporter.cpp:(.text._ZN4llvm2cl3optIiLb0ENS0_6parserIiEEEC2IJA12_cNS0_4descENS0_10value_descENS0_3catENS0_3subENS0_11initializerIiEENS0_18NumOccurrencesFlagEEEEDpRKT_[_ZN4llvm2cl3optIiLb0ENS0_6parserIiEEEC5IJA12_cNS0_4descENS0_10value_descENS0_3catENS0_3subENS0_11initializerIiEENS0_18NumOccurrencesFlagEEEEDpRKT_]+0x4a): undefined reference to `vtable for llvm::cl::opt<int, false, llvm::cl::parser<int> >'
reporter.cpp:(.text._ZN4llvm2cl3optIiLb0ENS0_6parserIiEEEC2IJA12_cNS0_4descENS0_10value_descENS0_3catENS0_3subENS0_11initializerIiEENS0_18NumOccurrencesFlagEEEEDpRKT_[_ZN4llvm2cl3optIiLb0ENS0_6parserIiEEEC5IJA12_cNS0_4descENS0_10value_descENS0_3catENS0_3subENS0_11initializerIiEENS0_18NumOccurrencesFlagEEEEDpRKT_]+0xa7): undefined reference to `llvm::cl::opt<int, false, llvm::cl::parser<int> >::done()'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::opt<bool, false, llvm::cl::parser<bool> >::opt<char [16], llvm::cl::desc, llvm::cl::cat, llvm::cl::sub, llvm::cl::initializer<bool>, llvm::cl::NumOccurrencesFlag>(char const (&) [16], llvm::cl::desc const&, llvm::cl::cat const&, llvm::cl::sub const&, llvm::cl::initializer<bool> const&, llvm::cl::NumOccurrencesFlag const&)':
reporter.cpp:(.text._ZN4llvm2cl3optIbLb0ENS0_6parserIbEEEC2IJA16_cNS0_4descENS0_3catENS0_3subENS0_11initializerIbEENS0_18NumOccurrencesFlagEEEEDpRKT_[_ZN4llvm2cl3optIbLb0ENS0_6parserIbEEEC5IJA16_cNS0_4descENS0_3catENS0_3subENS0_11initializerIbEENS0_18NumOccurrencesFlagEEEEDpRKT_]+0x4a): undefined reference to `vtable for llvm::cl::opt<bool, false, llvm::cl::parser<bool> >'
reporter.cpp:(.text._ZN4llvm2cl3optIbLb0ENS0_6parserIbEEEC2IJA16_cNS0_4descENS0_3catENS0_3subENS0_11initializerIbEENS0_18NumOccurrencesFlagEEEEDpRKT_[_ZN4llvm2cl3optIbLb0ENS0_6parserIbEEEC5IJA16_cNS0_4descENS0_3catENS0_3subENS0_11initializerIbEENS0_18NumOccurrencesFlagEEEEDpRKT_]+0xa8): undefined reference to `llvm::cl::opt<bool, false, llvm::cl::parser<bool> >::done()'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `void llvm::cl::applicator<char [14]>::opt<llvm::cl::opt<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false, llvm::cl::parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >(llvm::StringRef, llvm::cl::opt<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false, llvm::cl::parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)':
reporter.cpp:(.text._ZN4llvm2cl10applicatorIA14_cE3optINS0_3optINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0ENS0_6parserISB_EEEEEEvNS_9StringRefERT_[_ZN4llvm2cl10applicatorIA14_cE3optINS0_3optINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0ENS0_6parserISB_EEEEEEvNS_9StringRefERT_]+0x34): undefined reference to `llvm::cl::Option::setArgStr(llvm::StringRef)'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `void llvm::cl::applicator<char [12]>::opt<llvm::cl::opt<int, false, llvm::cl::parser<int> > >(llvm::StringRef, llvm::cl::opt<int, false, llvm::cl::parser<int> >&)':
reporter.cpp:(.text._ZN4llvm2cl10applicatorIA12_cE3optINS0_3optIiLb0ENS0_6parserIiEEEEEEvNS_9StringRefERT_[_ZN4llvm2cl10applicatorIA12_cE3optINS0_3optIiLb0ENS0_6parserIiEEEEEEvNS_9StringRefERT_]+0x34): undefined reference to `llvm::cl::Option::setArgStr(llvm::StringRef)'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `void llvm::cl::applicator<char [16]>::opt<llvm::cl::opt<bool, false, llvm::cl::parser<bool> > >(llvm::StringRef, llvm::cl::opt<bool, false, llvm::cl::parser<bool> >&)':
reporter.cpp:(.text._ZN4llvm2cl10applicatorIA16_cE3optINS0_3optIbLb0ENS0_6parserIbEEEEEEvNS_9StringRefERT_[_ZN4llvm2cl10applicatorIA16_cE3optINS0_3optIbLb0ENS0_6parserIbEEEEEEvNS_9StringRefERT_]+0x34): undefined reference to `llvm::cl::Option::setArgStr(llvm::StringRef)'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `void llvm::cl::initializer<bool>::apply<llvm::cl::opt<bool, false, llvm::cl::parser<bool> > >(llvm::cl::opt<bool, false, llvm::cl::parser<bool> >&) const':
reporter.cpp:(.text._ZNK4llvm2cl11initializerIbE5applyINS0_3optIbLb0ENS0_6parserIbEEEEEEvRT_[_ZNK4llvm2cl11initializerIbE5applyINS0_3optIbLb0ENS0_6parserIbEEEEEEvRT_]+0x22): undefined reference to `llvm::cl::opt<bool, false, llvm::cl::parser<bool> >::setInitialValue(bool const&)'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `void llvm::cl::initializer<int>::apply<llvm::cl::opt<int, false, llvm::cl::parser<int> > >(llvm::cl::opt<int, false, llvm::cl::parser<int> >&) const':
reporter.cpp:(.text._ZNK4llvm2cl11initializerIiE5applyINS0_3optIiLb0ENS0_6parserIiEEEEEEvRT_[_ZNK4llvm2cl11initializerIiE5applyINS0_3optIiLb0ENS0_6parserIiEEEEEEvRT_]+0x22): undefined reference to `llvm::cl::opt<int, false, llvm::cl::parser<int> >::setInitialValue(int const&)'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o:(.rodata._ZTVN4llvm2cl11OptionValueIbEE[_ZTVN4llvm2cl11OptionValueIbEE]+0x18): undefined reference to `llvm::cl::GenericOptionValue::anchor()'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o:(.rodata._ZTVN4llvm2cl15OptionValueBaseIbLb0EEE[_ZTVN4llvm2cl15OptionValueBaseIbLb0EEE]+0x18): undefined reference to `llvm::cl::GenericOptionValue::anchor()'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o:(.rodata._ZTVN4llvm2cl15OptionValueCopyIbEE[_ZTVN4llvm2cl15OptionValueCopyIbEE]+0x18): undefined reference to `llvm::cl::GenericOptionValue::anchor()'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o:(.rodata._ZTVN4llvm2cl11OptionValueIiEE[_ZTVN4llvm2cl11OptionValueIiEE]+0x18): undefined reference to `llvm::cl::GenericOptionValue::anchor()'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o:(.rodata._ZTVN4llvm2cl15OptionValueBaseIiLb0EEE[_ZTVN4llvm2cl15OptionValueBaseIiLb0EEE]+0x18): undefined reference to `llvm::cl::GenericOptionValue::anchor()'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o:(.rodata._ZTVN4llvm2cl15OptionValueCopyIiEE[_ZTVN4llvm2cl15OptionValueCopyIiEE]+0x18): more undefined references to `llvm::cl::GenericOptionValue::anchor()' follow
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::opt<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false, llvm::cl::parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~opt()':
reporter.cpp:(.text._ZN4llvm2cl3optINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0ENS0_6parserIS7_EEED2Ev[_ZN4llvm2cl3optINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0ENS0_6parserIS7_EEED5Ev]+0xd): undefined reference to `vtable for llvm::cl::opt<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false, llvm::cl::parser<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::opt<int, false, llvm::cl::parser<int> >::~opt()':
reporter.cpp:(.text._ZN4llvm2cl3optIiLb0ENS0_6parserIiEEED2Ev[_ZN4llvm2cl3optIiLb0ENS0_6parserIiEEED5Ev]+0xd): undefined reference to `vtable for llvm::cl::opt<int, false, llvm::cl::parser<int> >'
tools/reporter/CMakeFiles/mull-reporter.dir/reporter.cpp.o: In function `llvm::cl::opt<bool, false, llvm::cl::parser<bool> >::~opt()':
reporter.cpp:(.text._ZN4llvm2cl3optIbLb0ENS0_6parserIbEEED2Ev[_ZN4llvm2cl3optIbLb0ENS0_6parserIbEEED5Ev]+0xd): undefined reference to `vtable for llvm::cl::opt<bool, false, llvm::cl::parser<bool> >'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Makefile:70: recipe for target 'ninja.install.mull-driver' failed
make: *** [ninja.install.mull-driver] Error 1

**Comment by AlexDenisov** [comment] 2018-07-11 05:56
Which Linux distribution do you use?
First of all it seems like libsqlite is not installed.
As of LLVM linking issues - it is not yet clear to me what is wrong.

**Comment by Brick7Face** [comment] 2018-07-12 02:02
I'm using Ubuntu 18 but followed the docker instructions and am using the xenial container. I'm using LLVM 6.0 I believe, but I've tried it with 3.9 too. I tried reinstalling libsqlite and it's installed. What's weird is that the make test output seems to work okay, but make install doesn't want to create the driver.

**Comment by AlexDenisov** [comment] 2018-07-16 09:49
Hi @Brick7Face, I just tried to reproduce your case, but no luck so far.
Is there anything we might be missing?

**Comment by AlexDenisov** [comment] 2018-07-16 10:47
Ok, so it caused by gcc/g++. Please, try to compile everything with the clang. I.e.:
```
export CC=clang
export CXX=clang++
make ninja.init LLVM_ROOT=/usr/lib/llvm-6.0/
make install
```

I will (hopefully) investigate this issue in more details at some point.
@Brick7Face, I'm closing the issue assuming that it's fixed. Please reopen if it's not.

**Closed by AlexDenisov** 2018-07-16 10:47 UTC

**Comment by AlexDenisov** [comment] 2018-07-16 14:17
Thank you for your feedback, @Brick7Face.
I can suggest you look into these tools (in no particular order):

 - https://github.com/nlohmann/mutate_cpp
 - https://github.com/swtv-kaist/MUSIC
 - https://github.com/joakim-brannstrom/dextool

Also, you can keep an eye on this repo: https://github.com/theofidry/mutation-testing
New tools may appear there.

**Comment by Brick7Face** [comment] 2018-07-20 15:48
Thank you so much!!

**Comment by AlexDenisov** [comment] 2018-10-18 10:15
Hi @Brick7Face, the issue you had is resolved now, please check this piece of documentation: https://github.com/mull-project/mull/blob/master/Docs/HowToRunMull.md#known-build-issues

**Comment by Brick7Face** [comment] 2018-10-18 19:55
Awesome! I will check that out if I get a chance. I ended up using MUSIC for the part I needed, and that worked great. I really appreciate the follow-up!!
