### ISSUE TITLE
Installation failed on MacOS

### ISSUE THREAD

**Issue by BUAA-SUT** [mull-project/mull#1003] opened 2022-05-23 14:49 UTC
Run mull-runner-13, and throws the following exception:  

Reason: tried: '/usr/local/opt/llvm/lib/libLLVM.dylib' (no such file), '/usr/local/lib/libLLVM.dylib' (no such file), '/usr/lib/libLLVM.dylib' (no such file)

why is that?

**Comment by AlexDenisov** [comment] 2022-05-24 06:07
Hi @BUAA-SUT, Mull expects LLVM (from Homebrew) to be installed as it was built against that LLVM.
Could you install it and check if it works for you?

```
brew install llvm
```

**Comment by BUAA-SUT** [comment] 2022-05-24 06:36
Thank you for your quick reply.

But I've already installed LLVM

rendaixu@rendaixudeMacBook-Pro ~ % llvm-config --version
9.0.0
rendaixu@rendaixudeMacBook-Pro ~ % which llvm-config
/usr/local/bin/llvm-config

**Comment by AlexDenisov** [comment] 2022-05-25 19:41
@BUAA-SUT `13` in the binary name means the version of LLVM Mull was built against. If you want to use LLVM 9, then you would have to obtain `mull-9` and probably adjust the binaries to point to your LLVM installation using `install_name_tool`, e.g.:

```bash
> install_name_tool -change /usr/local/opt/llvm@9/lib/libLLVM.dylib <path-to-your-llvm9.dylib> /usr/local/bin/mull-runner-9
> install_name_tool -change /usr/local/opt/llvm@9/lib/libLLVM.dylib <path-to-your-llvm9.dylib> /usr/local/lib/mull-ir-frontend-9
```

**Comment by BUAA-SUT** [comment] 2022-05-26 02:17
Sorry, I still can't install correctly.

rendaixu@rendaixudeMacBook-Pro ~ % install_name_tool -change /usr/local/opt/llvm@9/lib/libLLVM.dylib /usr/local/lib/libLLVM.dylib /usr/local/bin/mull-runner-9
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't create output file: /usr/local/bin/mull-runner-9.XXXXXX (Permission denied)
fatal error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: cannot rename /usr/local/bin/mull-runner-9 to /usr/local/bin/mull-runner-9.XXXXXX (No such file or directory)

What's wrong with my way？ Thank you

**Comment by AlexDenisov** [comment] 2022-05-27 09:09
As the errors say, you don't have permissions to create new files under `/usr/local/bin`.
You can try downloading mull binaries and modifying them in place before moving to `/usr/local/bin`.

Or the easiest option, get `mull-13` and install LLVM from Homebrew.

Yet another alternative approach: [build Mull from sources](https://mull.readthedocs.io/en/0.18.0/HackingOnMull.html#local-development-setup) against LLVM you have installed.

**Comment by AlexDenisov** [comment] 2022-08-27 21:48
Hi @BUAA-SUT, please feel free to reopen if the issue is still not resolved.

**Closed by AlexDenisov** 2022-08-27 21:48 UTC
